name: chat_seminar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.17.5
  firebase_core: ^2.32.0
  firebase_auth_web: ^5.8.14
  firebase_messaging: ^14.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
